### ISSUE TITLE
CNAME records shouldn't be allowed to point to themselves

### ISSUE THREAD

**Issue by remyd74** [jvns/mess-with-dns#30]
You cannot create a CNAME record to point to itself.
![image](https://github.com/jvns/mess-with-dns-backend/assets/83014185/5c5c3607-8044-4150-a66e-76fd4b64d34c)

**Comment by jvns** [comment]
I'm going to close this because I'm not convinced that allowing CNAME records to point themselves is a _problem_ exactly -- of course if you create a CNAME record that points to itself, it's going to resolve in an error like a SERVFAIL, but I think it's interesting to see what happens if you do that and I'd rather be permissive here.
