### ISSUE TITLE
Requests with type `ANY` return no records instead of returning all records for a domain

### ISSUE THREAD

**Issue by aaaaaa123456789** [jvns/mess-with-dns#34]
Simple example (without changing any records between requests):

![image](https://github.com/jvns/mess-with-dns-backend/assets/6129020/6f882148-91d4-47d5-8aca-c60308036b85)

**Comment by jvns** [comment]
Thanks, but closing because I decided intentionally not to support ANY (for the reasons Marek explains in https://blog.cloudflare.com/rfc8482-saying-goodbye-to-any)

**Comment by aaaaaa123456789** [comment]
Hey, thanks for the response! Might be a good idea to return a generic response the way Cloudflare does, so someone querying the server doesn't get confused like I did.

**Comment by jvns** [comment]
By a generic response, do you mean the `NOTIMP` response code? Here's what I see:

```
$ dig @1.1.1.1 any google.com +all
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOTIMP, id: 6164
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.			IN	ANY

;; Query time: 14 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sat Aug 17 11:48:04 EDT 2024
;; MSG SIZE  rcvd: 39
```

**Comment by aaaaaa123456789** [comment]
That works!

**Comment by jvns** [comment]
So I looked into this a little more and realized a few things:

1. It's actually pretty common for authoritative nameservers to support `ANY` queries
2. PowerDNS (the authoritative nameserver that Mess With DNS now uses, after a refactor) supports `ANY` queries
3. Since switching to PowerDNS as a backend this week, I think the policy I want to have is generally "make the same decisions  PowerDNS does about everything", since the PowerDNS folks have thought about DNS a lot more than me
4. The reason that `ANY` queries weren't working was a bug, fixed by connecting to PowerDNS over TCP instead of UDP

So now mess with dns should support ANY queries! You can see it with:

`dig @8.8.8.8  any messwithdns.com`
